/**
 * Hierarchical query key factory for all domains.
 * Ensures consistent key structuring and type-safe cache invalidation.
 */

export const queryKeys = {
  auth: {
    all: ['auth'] as const,
    me: () => ['auth', 'me'] as const,
    organizations: () => ['auth', 'organizations'] as const,
    currentOrganization: () => ['auth', 'organizations', 'current'] as const,
    sessions: () => ['auth', 'sessions'] as const,
  },

  customer: {
    all: ['customer'] as const,
    profile: () => ['customer', 'profile'] as const,
    addresses: () => ['customer', 'addresses'] as const,
    address: (id: string) => ['customer', 'addresses', id] as const,
    bookings: (params?: Record<string, unknown>) => ['customer', 'bookings', params] as const,
    booking: (id: string) => ['customer', 'bookings', 'detail', id] as const,
    orders: (params?: Record<string, unknown>) => ['customer', 'orders', params] as const,
    order: (id: string) => ['customer', 'orders', 'detail', id] as const,
    favorites: () => ['customer', 'favorites'] as const,
    rewards: () => ['customer', 'rewards'] as const,
    coupons: () => ['customer', 'coupons'] as const,
    offers: () => ['customer', 'offers'] as const,
    paymentMethods: () => ['customer', 'payment-methods'] as const,
  },

  provider: {
    all: ['provider'] as const,
    profile: () => ['provider', 'profile'] as const,
    services: (params?: Record<string, unknown>) => ['provider', 'services', params] as const,
    service: (id: string) => ['provider', 'services', 'detail', id] as const,
    serviceAreas: (params?: Record<string, unknown>) => ['provider', 'service-areas', params] as const,
    serviceArea: (id: string) => ['provider', 'service-areas', 'detail', id] as const,
    availability: () => ['provider', 'availability'] as const,
    documents: (params?: Record<string, unknown>) => ['provider', 'documents', params] as const,
    document: (id: string) => ['provider', 'documents', 'detail', id] as const,
    bookings: (params?: Record<string, unknown>) => ['provider', 'bookings', params] as const,
    booking: (id: string) => ['provider', 'bookings', 'detail', id] as const,
    bookingStatusHistory: (id: string) => ['provider', 'bookings', id, 'status-history'] as const,
    bookingNotes: (id: string) => ['provider', 'bookings', id, 'notes'] as const,
    assignments: (params?: Record<string, unknown>) => ['provider', 'assignments', params] as const,
    assignment: (id: string) => ['provider', 'assignments', 'detail', id] as const,
    assignmentHistory: (id: string) => ['provider', 'assignments', id, 'history'] as const,
    orders: (params?: Record<string, unknown>) => ['provider', 'orders', params] as const,
    order: (id: string) => ['provider', 'orders', 'detail', id] as const,
    earnings: (params?: Record<string, unknown>) => ['provider', 'earnings', params] as const,
    earningsSummary: () => ['provider', 'earnings', 'summary'] as const,
    earningTransactions: (id: string) => ['provider', 'earnings', id, 'transactions'] as const,
    payouts: (params?: Record<string, unknown>) => ['provider', 'payouts', params] as const,
    reviews: (params?: Record<string, unknown>) => ['provider', 'reviews', params] as const,
    reviewSummary: () => ['provider', 'reviews', 'summary'] as const,
    review: (id: string) => ['provider', 'reviews', 'detail', id] as const,
    notifications: (params?: Record<string, unknown>) => ['provider', 'notifications', params] as const,
    notificationUnreadCount: () => ['provider', 'notifications', 'unread-count'] as const,
    notificationPreferences: () => ['provider', 'notifications', 'preferences'] as const,
    supportTickets: (params?: Record<string, unknown>) => ['provider', 'support', 'tickets', params] as const,
    supportTicket: (id: string) => ['provider', 'support', 'tickets', 'detail', id] as const,
    supportTicketMessages: (id: string) => ['provider', 'support', 'tickets', id, 'messages'] as const,
    disputes: (params?: Record<string, unknown>) => ['provider', 'disputes', params] as const,
    dispute: (id: string) => ['provider', 'disputes', 'detail', id] as const,
    disputeMessages: (id: string) => ['provider', 'disputes', id, 'messages'] as const,
    disputeEvidence: (id: string) => ['provider', 'disputes', id, 'evidence'] as const,
  },

  deliveryPartner: {
    all: ['deliveryPartner'] as const,
    profile: () => ['deliveryPartner', 'profile'] as const,
    serviceAreas: (params?: Record<string, unknown>) => ['deliveryPartner', 'service-areas', params] as const,
    serviceArea: (id: string) => ['deliveryPartner', 'service-areas', 'detail', id] as const,
    availability: () => ['deliveryPartner', 'availability'] as const,
    documents: (params?: Record<string, unknown>) => ['deliveryPartner', 'documents', params] as const,
    document: (id: string) => ['deliveryPartner', 'documents', 'detail', id] as const,
    assignments: (params?: Record<string, unknown>) => ['deliveryPartner', 'assignments', params] as const,
    assignment: (id: string) => ['deliveryPartner', 'assignments', 'detail', id] as const,
    assignmentHistory: (id: string) => ['deliveryPartner', 'assignments', id, 'history'] as const,
    deliveryJob: (id: string) => ['deliveryPartner', 'delivery-jobs', 'detail', id] as const,
    deliveryEvents: (id: string) => ['deliveryPartner', 'delivery-jobs', id, 'events'] as const,
    earnings: (params?: Record<string, unknown>) => ['deliveryPartner', 'earnings', params] as const,
    earningsSummary: () => ['deliveryPartner', 'earnings', 'summary'] as const,
    earningTransactions: (id: string) => ['deliveryPartner', 'earnings', id, 'transactions'] as const,
    notifications: (params?: Record<string, unknown>) => ['deliveryPartner', 'notifications', params] as const,
    notificationUnreadCount: () => ['deliveryPartner', 'notifications', 'unread-count'] as const,
    notificationPreferences: () => ['deliveryPartner', 'notifications', 'preferences'] as const,
    supportTickets: (params?: Record<string, unknown>) => ['deliveryPartner', 'support', 'tickets', params] as const,
    supportTicket: (id: string) => ['deliveryPartner', 'support', 'tickets', 'detail', id] as const,
    supportTicketMessages: (id: string) => ['deliveryPartner', 'support', 'tickets', id, 'messages'] as const,
    disputes: (params?: Record<string, unknown>) => ['deliveryPartner', 'disputes', params] as const,
    dispute: (id: string) => ['deliveryPartner', 'disputes', 'detail', id] as const,
    disputeMessages: (id: string) => ['deliveryPartner', 'disputes', id, 'messages'] as const,
    disputeEvidence: (id: string) => ['deliveryPartner', 'disputes', id, 'evidence'] as const,
  },

  delivery: {
    all: ['delivery'] as const,
    profile: () => ['delivery', 'profile'] as const,
    tasks: (params?: Record<string, unknown>) => ['delivery', 'tasks', params] as const,
    task: (id: string) => ['delivery', 'tasks', 'detail', id] as const,
    schedule: () => ['delivery', 'schedule'] as const,
    earnings: (params?: Record<string, unknown>) => ['delivery', 'earnings', params] as const,
    history: (params?: Record<string, unknown>) => ['delivery', 'history', params] as const,
  },

  admin: {
    all: ['admin'] as const,
    dashboard: () => ['admin', 'dashboard'] as const,
    organization: () => ['admin', 'organization'] as const,
    members: (params?: Record<string, unknown>) => ['admin', 'members', params] as const,
    member: (id: string) => ['admin', 'members', 'detail', id] as const,
    users: (params?: Record<string, unknown>) => ['admin', 'users', params] as const,
    user: (id: string) => ['admin', 'users', 'detail', id] as const,
    customers: (params?: Record<string, unknown>) => ['admin', 'customers', params] as const,
    customer: (id: string) => ['admin', 'customers', 'detail', id] as const,
    providers: (params?: Record<string, unknown>) => ['admin', 'providers', params] as const,
    provider: (id: string) => ['admin', 'providers', 'detail', id] as const,
    deliveryPartners: (params?: Record<string, unknown>) => ['admin', 'delivery-partners', params] as const,
    deliveryPartner: (id: string) => ['admin', 'delivery-partners', 'detail', id] as const,
    bookings: (params?: Record<string, unknown>) => ['admin', 'bookings', params] as const,
    booking: (id: string) => ['admin', 'bookings', 'detail', id] as const,
    bookingHistory: (id: string) => ['admin', 'bookings', 'history', id] as const,
    assignments: (params?: Record<string, unknown>) => ['admin', 'assignments', params] as const,
    assignment: (id: string) => ['admin', 'assignments', 'detail', id] as const,
    catalog: {
      categories: (params?: Record<string, unknown>) => ['admin', 'catalog', 'categories', params] as const,
      category: (id: string) => ['admin', 'catalog', 'categories', 'detail', id] as const,
      services: (params?: Record<string, unknown>) => ['admin', 'catalog', 'services', params] as const,
      service: (id: string) => ['admin', 'catalog', 'services', 'detail', id] as const,
    },
    payments: (params?: Record<string, unknown>) => ['admin', 'payments', params] as const,
    payment: (id: string) => ['admin', 'payments', 'detail', id] as const,
    transactions: (params?: Record<string, unknown>) => ['admin', 'transactions', params] as const,
    transaction: (id: string) => ['admin', 'transactions', 'detail', id] as const,
    refunds: (params?: Record<string, unknown>) => ['admin', 'refunds', params] as const,
    refund: (id: string) => ['admin', 'refunds', 'detail', id] as const,
    earnings: (params?: Record<string, unknown>) => ['admin', 'earnings', params] as const,
    earning: (id: string) => ['admin', 'earnings', 'detail', id] as const,
    reviews: (params?: Record<string, unknown>) => ['admin', 'reviews', params] as const,
    review: (id: string) => ['admin', 'reviews', 'detail', id] as const,
    reviewReports: (params?: Record<string, unknown>) => ['admin', 'reviews', 'reports', params] as const,
    notifications: (params?: Record<string, unknown>) => ['admin', 'notifications', params] as const,
    notification: (id: string) => ['admin', 'notifications', 'detail', id] as const,
    notificationTemplates: () => ['admin', 'notifications', 'templates'] as const,
    communications: (params?: Record<string, unknown>) => ['admin', 'communications', params] as const,
    support: (params?: Record<string, unknown>) => ['admin', 'support', params] as const,
    supportTicket: (id: string) => ['admin', 'support', 'detail', id] as const,
    disputes: (params?: Record<string, unknown>) => ['admin', 'disputes', params] as const,
    dispute: (id: string) => ['admin', 'disputes', 'detail', id] as const,
    audit: (params?: Record<string, unknown>) => ['admin', 'audit', params] as const,
    auditEvent: (id: string) => ['admin', 'audit', 'detail', id] as const,
    search: (query?: string, params?: Record<string, unknown>) => ['admin', 'search', query, params] as const,
    reports: (type?: string, params?: Record<string, unknown>) => ['admin', 'reports', type, params] as const,
  },

  catalog: {
    all: ['catalog'] as const,
    categories: () => ['catalog', 'categories'] as const,
    category: (slug: string) => ['catalog', 'categories', slug] as const,
    services: (params?: Record<string, unknown>) => ['catalog', 'services', params] as const,
    service: (id: string) => ['catalog', 'services', 'detail', id] as const,
  },

  notifications: {
    all: ['notifications'] as const,
    list: (params?: Record<string, unknown>) => ['notifications', 'list', params] as const,
    preferences: () => ['notifications', 'preferences'] as const,
    unreadCount: () => ['notifications', 'unread-count'] as const,
  },

  support: {
    all: ['support'] as const,
    tickets: (params?: Record<string, unknown>) => ['support', 'tickets', params] as const,
    ticket: (id: string) => ['support', 'tickets', 'detail', id] as const,
  },

  disputes: {
    all: ['disputes'] as const,
    list: (params?: Record<string, unknown>) => ['disputes', 'list', params] as const,
    detail: (id: string) => ['disputes', 'detail', id] as const,
  },

  reviews: {
    all: ['reviews'] as const,
    list: (params?: Record<string, unknown>) => ['reviews', 'list', params] as const,
    detail: (id: string) => ['reviews', 'detail', id] as const,
    booking: (bookingId: string) => ['reviews', 'booking', bookingId] as const,
  },
} as const;

