/**
 * ============================================================================
 * WASHORA Phase B11: Promotions, Coupons & Customer Rewards Types
 * ============================================================================
 */

export enum PromotionErrorCode {
  // Coupon Errors
  COUPON_NOT_FOUND = 'COUPON_NOT_FOUND',
  COUPON_INACTIVE = 'COUPON_INACTIVE',
  COUPON_EXPIRED = 'COUPON_EXPIRED',
  COUPON_NOT_STARTED = 'COUPON_NOT_STARTED',
  COUPON_USAGE_LIMIT_REACHED = 'COUPON_USAGE_LIMIT_REACHED',
  COUPON_CUSTOMER_LIMIT_REACHED = 'COUPON_CUSTOMER_LIMIT_REACHED',
  COUPON_MINIMUM_ORDER_NOT_MET = 'COUPON_MINIMUM_ORDER_NOT_MET',
  COUPON_NOT_ELIGIBLE = 'COUPON_NOT_ELIGIBLE',
  COUPON_ALREADY_REDEEMED = 'COUPON_ALREADY_REDEEMED',
  COUPON_INVALID_TRANSITION = 'COUPON_INVALID_TRANSITION',
  COUPON_CODE_DUPLICATE = 'COUPON_CODE_DUPLICATE',

  // Offer Errors
  OFFER_NOT_FOUND = 'OFFER_NOT_FOUND',
  OFFER_INACTIVE = 'OFFER_INACTIVE',
  OFFER_EXPIRED = 'OFFER_EXPIRED',
  OFFER_NOT_STARTED = 'OFFER_NOT_STARTED',
  OFFER_NOT_ELIGIBLE = 'OFFER_NOT_ELIGIBLE',
  OFFER_USAGE_LIMIT_REACHED = 'OFFER_USAGE_LIMIT_REACHED',
  OFFER_CUSTOMER_LIMIT_REACHED = 'OFFER_CUSTOMER_LIMIT_REACHED',
  OFFER_ALREADY_REDEEMED = 'OFFER_ALREADY_REDEEMED',
  OFFER_INVALID_TRANSITION = 'OFFER_INVALID_TRANSITION',

  // General Promotion & Stacking Errors
  PROMOTION_ALREADY_APPLIED = 'PROMOTION_ALREADY_APPLIED',
  PROMOTION_DISCOUNT_INVALID = 'PROMOTION_DISCOUNT_INVALID',
  PROMOTION_ACCESS_DENIED = 'PROMOTION_ACCESS_DENIED',

  // Reward Account & Ledger Errors
  REWARD_ACCOUNT_NOT_FOUND = 'REWARD_ACCOUNT_NOT_FOUND',
  REWARD_ACCOUNT_FROZEN = 'REWARD_ACCOUNT_FROZEN',
  REWARD_ACCOUNT_CLOSED = 'REWARD_ACCOUNT_CLOSED',
  INSUFFICIENT_REWARD_BALANCE = 'INSUFFICIENT_REWARD_BALANCE',
  INVALID_REWARD_AMOUNT = 'INVALID_REWARD_AMOUNT',
  REWARD_NOT_ELIGIBLE = 'REWARD_NOT_ELIGIBLE',
  REWARD_ALREADY_EARNED = 'REWARD_ALREADY_EARNED',
  REWARD_TRANSACTION_IMMUTABLE = 'REWARD_TRANSACTION_IMMUTABLE',
  REWARD_TRANSACTION_NOT_FOUND = 'REWARD_TRANSACTION_NOT_FOUND',
  REWARD_ACCESS_DENIED = 'REWARD_ACCESS_DENIED',

  // Idempotency
  IDEMPOTENCY_KEY_CONFLICT = 'IDEMPOTENCY_KEY_CONFLICT',
}

export enum DiscountType {
  PERCENTAGE = 'PERCENTAGE',
  FIXED_AMOUNT = 'FIXED_AMOUNT',
}

export enum CouponStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  EXPIRED = 'EXPIRED',
  DISABLED = 'DISABLED',
}

export enum OfferStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  EXPIRED = 'EXPIRED',
  DISABLED = 'DISABLED',
}

export enum OfferType {
  WELCOME = 'WELCOME',
  SEASONAL = 'SEASONAL',
  FIRST_BOOKING = 'FIRST_BOOKING',
  SERVICE_SPECIFIC = 'SERVICE_SPECIFIC',
  CATEGORY_SPECIFIC = 'CATEGORY_SPECIFIC',
  LOYALTY = 'LOYALTY',
  GENERAL = 'GENERAL',
}

export enum RewardAccountStatus {
  ACTIVE = 'ACTIVE',
  FROZEN = 'FROZEN',
  CLOSED = 'CLOSED',
}

export enum RewardTransactionType {
  EARNED = 'EARNED',
  REDEEMED = 'REDEEMED',
  ADJUSTED = 'ADJUSTED',
  EXPIRED = 'EXPIRED',
  REFUNDED = 'REFUNDED',
}

export enum RewardTransactionStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  REVERSED = 'REVERSED',
}

export const PromotionAuditEvent = {
  COUPON_CREATED: 'COUPON_CREATED',
  COUPON_UPDATED: 'COUPON_UPDATED',
  COUPON_ACTIVATED: 'COUPON_ACTIVATED',
  COUPON_PAUSED: 'COUPON_PAUSED',
  COUPON_DISABLED: 'COUPON_DISABLED',
  COUPON_REDEEMED: 'COUPON_REDEEMED',
  COUPON_REMOVED: 'COUPON_REMOVED',

  OFFER_CREATED: 'OFFER_CREATED',
  OFFER_UPDATED: 'OFFER_UPDATED',
  OFFER_ACTIVATED: 'OFFER_ACTIVATED',
  OFFER_PAUSED: 'OFFER_PAUSED',
  OFFER_DISABLED: 'OFFER_DISABLED',
  OFFER_REDEEMED: 'OFFER_REDEEMED',

  REWARD_ACCOUNT_CREATED: 'REWARD_ACCOUNT_CREATED',
  REWARD_EARNED: 'REWARD_EARNED',
  REWARD_REDEEMED: 'REWARD_REDEEMED',
  REWARD_ADJUSTED: 'REWARD_ADJUSTED',
  REWARD_REVERSED: 'REWARD_REVERSED',

  PROMOTION_ACCESS_DENIED: 'PROMOTION_ACCESS_DENIED',
  REWARD_ACCESS_DENIED: 'REWARD_ACCESS_DENIED',
} as const;

/**
 * Valid state transitions for Coupon lifecycle
 */
export const VALID_COUPON_TRANSITIONS: Record<CouponStatus, CouponStatus[]> = {
  [CouponStatus.DRAFT]: [CouponStatus.ACTIVE, CouponStatus.DISABLED],
  [CouponStatus.ACTIVE]: [CouponStatus.PAUSED, CouponStatus.EXPIRED, CouponStatus.DISABLED],
  [CouponStatus.PAUSED]: [CouponStatus.ACTIVE, CouponStatus.DISABLED],
  [CouponStatus.EXPIRED]: [], // Terminal: Expired coupons cannot become redeemable again
  [CouponStatus.DISABLED]: [], // Terminal: Disabled coupons cannot be reopened
};

/**
 * Valid state transitions for Promotional Offer lifecycle
 */
export const VALID_OFFER_TRANSITIONS: Record<OfferStatus, OfferStatus[]> = {
  [OfferStatus.DRAFT]: [OfferStatus.ACTIVE, OfferStatus.DISABLED],
  [OfferStatus.ACTIVE]: [OfferStatus.PAUSED, OfferStatus.EXPIRED, OfferStatus.DISABLED],
  [OfferStatus.PAUSED]: [OfferStatus.ACTIVE, OfferStatus.DISABLED],
  [OfferStatus.EXPIRED]: [],
  [OfferStatus.DISABLED]: [],
};
