/**
 * Provider Domain Types & Constants
 * Reference: DB0 schema & Phase B5 specifications
 */

export enum ProviderErrorCode {
  PROVIDER_NOT_FOUND = 'PROVIDER_NOT_FOUND',
  PROVIDER_INACTIVE = 'PROVIDER_INACTIVE',
  PROVIDER_SUSPENDED = 'PROVIDER_SUSPENDED',
  SERVICE_NOT_FOUND = 'SERVICE_NOT_FOUND',
  SERVICE_NOT_AVAILABLE = 'SERVICE_NOT_AVAILABLE',
  PROVIDER_SERVICE_NOT_FOUND = 'PROVIDER_SERVICE_NOT_FOUND',
  PROVIDER_SERVICE_ALREADY_EXISTS = 'PROVIDER_SERVICE_ALREADY_EXISTS',
  SERVICE_AREA_NOT_FOUND = 'SERVICE_AREA_NOT_FOUND',
  SERVICE_AREA_ALREADY_EXISTS = 'SERVICE_AREA_ALREADY_EXISTS',
  AVAILABILITY_NOT_FOUND = 'AVAILABILITY_NOT_FOUND',
  AVAILABILITY_CONFLICT = 'AVAILABILITY_CONFLICT',
  DOCUMENT_NOT_FOUND = 'DOCUMENT_NOT_FOUND',
  DOCUMENT_INVALID = 'DOCUMENT_INVALID',
  DOCUMENT_STATE_INVALID = 'DOCUMENT_STATE_INVALID',
  PROVIDER_ACCESS_DENIED = 'PROVIDER_ACCESS_DENIED',
}

export enum ProviderAuditEventType {
  PROVIDER_PROFILE_UPDATED = 'PROVIDER_PROFILE_UPDATED',
  PROVIDER_SERVICE_ADDED = 'PROVIDER_SERVICE_ADDED',
  PROVIDER_SERVICE_UPDATED = 'PROVIDER_SERVICE_UPDATED',
  PROVIDER_SERVICE_DISABLED = 'PROVIDER_SERVICE_DISABLED',
  PROVIDER_SERVICE_REMOVED = 'PROVIDER_SERVICE_REMOVED',
  PROVIDER_SERVICE_AREA_CREATED = 'PROVIDER_SERVICE_AREA_CREATED',
  PROVIDER_SERVICE_AREA_UPDATED = 'PROVIDER_SERVICE_AREA_UPDATED',
  PROVIDER_SERVICE_AREA_REMOVED = 'PROVIDER_SERVICE_AREA_REMOVED',
  PROVIDER_AVAILABILITY_CREATED = 'PROVIDER_AVAILABILITY_CREATED',
  PROVIDER_AVAILABILITY_UPDATED = 'PROVIDER_AVAILABILITY_UPDATED',
  PROVIDER_AVAILABILITY_REMOVED = 'PROVIDER_AVAILABILITY_REMOVED',
  PROVIDER_DOCUMENT_SUBMITTED = 'PROVIDER_DOCUMENT_SUBMITTED',
  PROVIDER_DOCUMENT_REMOVED = 'PROVIDER_DOCUMENT_REMOVED',
}
